- name: provision aws resources
  hosts: localhost
  remote_user: ubuntu

  tasks:
    - name: launch cloudformation
      cloudformation:
        stack_name: "telemetry-lambda-cloudformation"
        state: "present"
        region: "us-west-2"
        disable_rollback: true
        template: "files/cloudformation.json"
        tags:
          Type: "spark"
          App: "pipeline"
      register: cloudformation

    - debug: var=cloudformation
    - command: files/deploy.sh "{{account}}:role/{{cloudformation.stack_outputs.Role}}"
